#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

cp system/blockMeshDict.orig system/blockMeshDict
runApplication blockMesh
runApplication setFields
#runApplication decomposePar
#runParallel    $application
runApplication		$application
#runApplication reconstructPar
touch foam.foam
#( cd validation && ./createGraphs )

#------------------------------------------------------------------------------
